Fix use of undeclared identifier 'as_nr'
Guard usage of as_nr by #ifdef CONFIG_MALI_DEBUG to avoid the following
error:

mali_kbase/mali_kbase_ctx_sched.c:324:22: error: use of undeclared identifier 'as_nr'
                KBASE_DEBUG_ASSERT(as_nr >= 0);
                                   ^

Fixes: f21fbb4 ("Restore some unused-but-set-variables if needed")
Signed-off-by: Daniel Mentz <danielmentz@google.com>
Change-Id: Ifa0f0b2113f42df73c8d56161bf0e137c696e2e9